server.port=8081

spring.application.name=shop
spring.datasource.url=jdbc:postgresql://localhost:5432/magnum
spring.datasource.username=postgres
spring.datasource.password=%5isBES%SE

spring.jpa.hibernate.ddl-auto=validate